import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import type { Metadata } from "next";
import { Data } from "@/components/data";
import Image from "next/image";
import { AiOutlineMore } from "react-icons/ai";

export const metadata: Metadata = {
  title: "Deactivate Colleague",
  description: "Generated by create next app",
};

export default function DeactivateColleague() {
  return (
    <div>
      <Table>
        <TableHeader>
          <TableRow className="bg-gray-200 text-center ">
            <TableHead className="font-normal text-black text-left pl-7 ">Name</TableHead>
            <TableHead className="font-normal text-black">Job title</TableHead>
            <TableHead className="font-normal text-black">Department</TableHead>
            <TableHead className="font-normal text-black">Status</TableHead>
            <TableHead className="font-normal text-black">Roles</TableHead>
            <TableHead className="font-normal text-black"></TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {Data.map((data, index) => (
            <TableRow key={index}>
              <TableCell className={`flex gap-2 items-center  ${data.status === 'Inactive' ? 'opacity-50 pointer-events-none' : ''} pl-7`}> 
                <Image 
                  src={data.image} 
                  alt="profile" 
                  width={48} 
                  height={48} 
                  className="rounded-full" 
                />
                {data.name}
              </TableCell>
              <TableCell className={data.status === 'Inactive' ? 'opacity-50 pointer-events-none' : ''}>{data.jobTitle}</TableCell>
              <TableCell className={data.status === 'Inactive' ? 'opacity-50 pointer-events-none' : ''}>{data.department}</TableCell>
              <TableCell>
                <span className={
                  data.status === 'Active' ? 'rounded-xl border-1 px-2 py-1 text-[#17B26A] bg-[#E9F0E7] font-normal' :
                  data.status === 'Pending' ? 'rounded-xl border-1 py-1 px-2 text-[#F79009] bg-[#FEF4E6] font-normal' :
                  data.status === 'Inactive' ? 'rounded-xl border-1 py-1 px-2 text-[#DA3E33] bg-[#FDEEE9] font-normal' :
                  'rounded-xl border-1 py-1 px-2 text-[#DA3E33] bg-[#FDEEE9] font-normal'
                }>
                  {data.status}
                </span>
              </TableCell>
              <TableCell className={data.status === 'Inactive' ? 'opacity-50 pointer-events-none' : ''}>
                <span className="rounded-xl border-1 py-1 px-2 text-[#DA3E33] bg-[#FDEEE9] font-normal">{data.roles}</span>
                <span className="text-black ml-2 rounded-xl border-1 py-1 px-2 bg-[#EAECF0]">+2</span>
              </TableCell>
              <TableCell className={`font-bold ${data.status === 'Inactive' ? 'opacity-50 pointer-events-none' : ''}`}><AiOutlineMore /></TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}